### ISSUE TITLE
Crash when moving items with crafting at the same time

### ISSUE THREAD

**Issue by cem3cem3** [cem3cem3/AppliedEcogisticsIssues#13]
r1rider01:
Getting this error when shift dragging a stack of iron into an Accessor, that is connected to some blast furnances.

--BEGIN DUMP--
Dump Time
02/26/2020 23:37:06

Exception
Exception: InvalidOperationException
Message:Changes could not be applied, the requested operation would result in an invalid inventory state: Inventory does not contain the items requested to be removed
Source:Eco.Gameplay

System.InvalidOperationException: Changes could not be applied, the requested operation would result in an invalid inventory state: Inventory does not contain the items requested to be removed
at Eco.Gameplay.Items.InventoryChangeSet.ApplyInternal(Boolean throwOnInvalid)
at Eco.Gameplay.Items.Inventory.Modify(Action1 callback, User user)
at Eco.Gameplay.Items.WorkOrder.TryToContributeItems(User actor, Inventory inventory)
at Eco.Gameplay.Components.CraftingComponent.AddResourcesToWorkOrders(User owner, User actor, Inventory source)
at Eco.Gameplay.Components.CraftingComponent.FindAndAddResourcesToWorkOrders(User actor)
at Eco.Gameplay.Components.CraftingComponent.Tick()
at Eco.Shared.Utils.ListExtensions.ForEach[T](IList1 list, Action1 action)
at Eco.Gameplay.Objects.WorldObject.Tick()
at Eco.Shared.Utils.EnumerableExtensions.ForEach[T](IEnumerable1 enumeration, Action`1 action)
at Eco.Gameplay.Objects.WorldObjectManager.Run()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart()

--END DUMP--

**Comment by r1rider01** [comment]
Ok so more on this:  seems to happen when a job needs more than is available in the accessor.

**Comment by cem3cem3** [comment]
I still have no luck reproducing this.
I hope this was fixed while fixing unrelated bugs, so let me know if this still happens in the new version.
