### ISSUE TITLE
Crash on server startup

### ISSUE THREAD

**Issue by SmokeyMcBeard** [cem3cem3/AppliedEcogisticsIssues#15]
[21:25:33.451] [1] [ Info] [Eco] Failed to load server, Exception was Exception: KeyNotFoundException
Message:The given key was not present in the dictionary.
Source:mscorlib

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
  at System.ThrowHelper.ThrowKeyNotFoundException()
  at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
  at Eco.ModKit.ModDataSync.GetItemInfos(Type itemType)
  at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
  at Eco.Shared.Utils.EnumerableExtensions.ToBson(IEnumerable enumeration, INetClient client)
  at Eco.ModKit.ModDataSync.PackModData()
  at Eco.ModKit.ModKitPlugin.Initialize(TimedTask timer)
  at InitializePlugins_Patch1(Object )
  at Eco.Server.PluginManager..ctor()
  at Eco.Server.Startup.Start(String[] args)

**Comment by cem3cem3** [comment]
Did this happen on a normal restart of the server or when migrating from an old mod version to a newer one? 
Because currently migrations are very finicky.

**Comment by SmokeyMcBeard** [comment]
Downloaded for first time ever. Put in mods. Started server. Got error.
Tried 2 previous versions after. Same error. Other mods have worked fine.
Moved other mods out of directory (nowhere near eco) and tried vanilla with
just your mod. Same error.

**Comment by SmokeyMcBeard** [comment]
I missed a mod and it was causing this mod to error. My fault. You can delete this issue.
