### ISSUE TITLE
Failed to load server, Exception was Exception: KeyNotFoundException

### ISSUE THREAD

**Issue by Sephiroth91** [cem3cem3/AppliedEcogisticsIssues#16]
Failed to load server, Exception was Exception: KeyNotFoundException
Message:Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
Source:mscorlib

System.Collections.Generic.KeyNotFoundException: Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
at System.ThrowHelper.ThrowKeyNotFoundException()
at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
at Eco.ModKit.ModDataSync.GetItemInfos(Type itemType)
at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
at Eco.Shared.Utils.EnumerableExtensions.ToBson(IEnumerable enumeration, INetClient client)
at Eco.ModKit.ModDataSync.PackModData()
at Eco.ModKit.ModKitPlugin.Initialize(TimedTask timer)
at InitializePlugins_Patch1(Object )
at Eco.Server.PluginManager..ctor()
at Eco.Server.Startup.Start(String[] args)

**Comment by cem3cem3** [comment]
I have had a very similar report recently with the same error #15 saying that in the end it was another mod.
Please make sure to try a clean install of the server without any other mods and let me know if the issue persists.

**Comment by BrysonZimmerman** [comment]
Fresh install, tried to connect to the server for the first time. On downloading mods, received the following

```Disconnected with error: Server encountered an exception:

<size=60.00%>Exception: KeyNotFoundException
Message:The given key 'ItemPipe.unity3d' was not present in the dictionary.
Source:mscorlib

System.Collections.Generic.KeyNotFoundException: The given key 'ItemPipe.unity3d' was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x0001e] in <b0dd258eb94b44a48f94659a34d3da02>:0 
  at Eco.ModKit.ModContentSync.SendContentFiles (System.Collections.Generic.List`1[T] requestList, Eco.Shared.Networking.INetClient targetClient) [0x00011] in <fd133b545e91407c989ec0b6980485ba>:0 
  at Eco.Plugins.Networking.Client.RequestContent (System.Collections.Generic.List`1[T] requestList) [0x0000e] in <3f846a4b5072495abd122789b36c43b3>:0 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <b0dd258eb94b44a48f94659a34d3da02>:0</size>
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
NetworkManager:OnClientDisconnected(String)
System.Action`1:Invoke(T)
Eco.Shared.Networking.NetworkClient:HandleDisconnect(String)
Eco.Shared.Networking.NetworkClient:HandleIncomingMessage(NetIncomingMessage)
Eco.Shared.Networking.NetworkClient:<Initialize>b__55_0()
Steamworks.PlayersRefreshComplete:Invoke()
System.Threading.SendOrPostCallback:Invoke(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
Steamworks.PlayersRefreshComplete:Invoke()```

**Comment by zoffixznet** [comment]
I was getting similar error:

![image](https://user-images.githubusercontent.com/5747918/78359259-b3be1a80-7582-11ea-8ad8-9c4c581a0f53.png)


Was able to fix it: I deleted Version.txt file and moved the "ItemSystem" folder directly into Mods folder (instead of it being inside another folder for this mod). Likely the second action is what fixed it.

Seems to have fixed it inasfar as I do see the Item skill show up in the research table, though haven't tried building and using the system yet.

**Comment by cem3cem3** [comment]
I find this very odd. In my testing server I have it simply as Mods -> ItemSystem -> the 3 mod files. This never caused an issue on my side and I have more than one mod installed. The text file is just there so others can keep track so that should be making absolutely no difference.

Looking at the error though, it seems to be on the side of eco trying to load data and failing, so check if there is some weird file path issue with special characters or similar. Unfortunately there is not much I can do since it seems the error occurs before the mod gets loaded.

**Comment by mastasytha** [comment]
I fixed this issue by renaming ItemSystem.dll to ItemPipe.dll

**Comment by cem3cem3** [comment]
Closing for the Eco 9.0.3 version.
