### ISSUE TITLE
Dedicated World failure after install

### ISSUE THREAD

**Issue by DMikulasr** [cem3cem3/AppliedEcogisticsIssues#25]
Added the latest files to my mod folder.

Both an existing world and new world generated this error. 

[19:07:25.416] [1] [ Info] [Eco] >>> START EcoServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null 
[19:07:25.433] [1] [ Info] [Eco] [Eco Server 0.9.2.2 beta release-149]
 
[19:07:25.474] [5] [ Info] [Eco] [Starting [PerformancePlugin]]...  
[19:07:25.474] [5] [ Info] [Eco] [Starting [PerformancePlugin]]... [Finished in 0.2ms]
 
[19:07:25.474] [5] [ Info] [Eco] [Server Initialization]...  
[19:07:25.834] [5] [ Info] [Eco] Starting LocalizationPlugin...  
[19:07:25.834] [5] [ Info] [Eco] Starting LocalizationPlugin... Finished in 0.2ms
 
[19:07:25.877] [5] [ Info] [Eco] Starting DifficultySettings...  
[19:07:25.877] [5] [ Info] [Eco] Starting DifficultySettings... Finished in 0.0ms
 
[19:07:25.877] [5] [ Info] [Eco] Loading mods...  
[19:07:32.928] [1] [ Info] [Eco] Mods recompiled with warnings.
 
[19:07:32.943] [1] [ Info] [Eco] Loading Eco.IntegrationTests...
 
[19:07:32.980] [1] [ Info] [Eco] Loading ItemSystem...
 
[19:07:34.090] [5] [ Info] [Eco] Loading mods... Finished in 8,208.1ms
 
[19:07:34.090] [5] [ Info] [Eco] [Server Initialization]... Finished in 8,615.7ms
 
[19:07:34.107] [1] [Error] [Eco] Unhandled errorSystem.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Plugins.Networking.NetworkManager.get_Config()
   at Eco.Server.Startup.SendIpc(String ipcMessage, Exception exception)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
   at Eco.Server.ApplicationHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Eco.Server.MainClass.Main(String[] args)

**Comment by cem3cem3** [comment]
Re-open this issue if this still happens with version 1.23.0.9.2.4E.
