### ISSUE TITLE
System.NullReferenceException in in NetworkManager

### ISSUE THREAD

**Issue by mimmordino** [cem3cem3/AppliedEcogisticsIssues#28]
Running server locally on my machine. Installed mod with version 9.2.4 of the game. Receive the following error from the logs:

[01:39:49.857] [1] [ Info] [Eco] >>> START EcoServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null 
[01:39:49.879] [1] [ Info] [Eco] [Eco Server 0.9.2.4 beta release-156]
 
[01:39:49.939] [5] [ Info] [Eco] [Starting [PerformancePlugin]]...  
[01:39:49.939] [5] [ Info] [Eco] [Starting [PerformancePlugin]]... [Finished in 0.4ms]
 
[01:39:49.939] [5] [ Info] [Eco] [Server Initialization]...  
[01:39:50.396] [5] [ Info] [Eco] Starting LocalizationPlugin...  
[01:39:50.396] [5] [ Info] [Eco] Starting LocalizationPlugin... Finished in 0.5ms
 
[01:39:50.426] [5] [ Info] [Eco] Starting DifficultySettings...  
[01:39:50.426] [5] [ Info] [Eco] Starting DifficultySettings... Finished in 0.0ms
 
[01:39:50.433] [5] [ Info] [Eco] Loading mods...  
[01:39:59.411] [1] [ Info] [Eco] Mods recompiled with warnings.
 
[01:39:59.431] [1] [ Info] [Eco] Loading BeekeepingMod1.1.0...
 
[01:39:59.431] [1] [ Info] [Eco] Loading Eco.IntegrationTests...
 
[01:39:59.431] [1] [ Info] [Eco] Loading ItemSystem...
 
[01:39:59.486] [5] [ Info] [Eco] Loading mods... Finished in 9,053.0ms
 
[01:39:59.486] [5] [ Info] [Eco] [Server Initialization]... Finished in 9,546.6ms
 
[01:39:59.514] [1] [Error] [Eco] Unhandled errorSystem.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Plugins.Networking.NetworkManager.get_Config()
   at Eco.Server.Startup.SendIpc(String ipcMessage, Exception exception)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
   at Eco.Server.ApplicationHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Eco.Server.MainClass.Main(String[] args)

**Comment by cem3cem3** [comment]
Please launch the server by using the Eco server executable, instead of using the client and report if there are any other issues when you do so.
SendIps failing is an Eco bug that occurs only if a mod fails to load and the server has been started through the client. Unfortunately this eats the real error that a mod may have caused, so there isn't much I can do with this as is.

**Comment by mimmordino** [comment]
I think I did this correctly but I'm not positive. See log below. I've also attached the log file from the server.
[ServerLog.txt](https://github.com/cem3cem3/AppliedEcogisticsIssues/files/6094486/ServerLog.txt)


C:\Program Files (x86)\Steam\steamapps\common\Eco\Eco_Data\Server>EcoServer.exe > ServerLog.txt
Unhandled exception. System.InvalidOperationException: 'overlapped' has already been freed.
   at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)

C:\Program Files (x86)\Steam\steamapps\common\Eco\Eco_Data\Server>

**Comment by mimmordino** [comment]
Removing the ItemPipe.unity3d and ItemSystem.dll from the mods folder allows the server to launch fine.

**Comment by D-Kay6** [comment]
Got the same problem.
No difference in error from this or #29 .
Version 1_22_0_9_2_1r does still work, so I'd suggest using that for now.

**Comment by cem3cem3** [comment]
Changing this issue to be for the first error and delegating the latter to issue #29. I have also notified game devs about the first, so it will hopefully be fixed in the next Eco release.

**Comment by cem3cem3** [comment]
Appears fixed in the base game with the new Eco version.
