### ISSUE TITLE
Crash when starting Solo not when starting server

### ISSUE THREAD

**Issue by Oddj0bs** [cem3cem3/AppliedEcogisticsIssues#32]
Here is log 

[14:24:56.956] [1] [ Info] [Eco] >>> START EcoServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null 
[14:24:56.969] [1] [ Info] [Eco] [Eco Server 0.9.3.1 beta release-204]
 
[14:24:57.009] [5] [ Info] [Eco] [Starting [PerformancePlugin]]...  
[14:24:57.009] [5] [ Info] [Eco] [Starting [PerformancePlugin]]... [Finished in 0,3ms]
 
[14:24:57.009] [5] [ Info] [Eco] [Server Initialization]...  
[14:24:57.397] [5] [ Info] [Eco] Starting LocalizationPlugin...  
[14:24:57.397] [5] [ Info] [Eco] Starting LocalizationPlugin... Finished in 0,2ms
 
[14:24:57.462] [5] [ Info] [Eco] Starting NetworkManager...  
[14:24:57.462] [5] [ Info] [Eco] Starting NetworkManager... Finished in 0,0ms
 
[14:24:57.762] [5] [ Info] [Eco] Starting DifficultySettings...  
[14:24:57.762] [5] [ Info] [Eco] Starting DifficultySettings... Finished in 0,0ms
 
[14:24:57.762] [5] [ Info] [Eco] Loading mods...  
[14:25:05.606] [1] [ Info] [Eco] Loading DisassemblyMod3.0.2...
 
[14:25:05.644] [1] [ Info] [Eco] Loading Eco.IntegrationTests...
 
[14:25:05.693] [1] [ Info] [Eco] Loading ItemSystem...
 
[14:25:06.136] [1] [Error] [Eco] Server is not running in 64 bit mode. Applied Ecogistics (ItemSystem) may not function correctly in this mode. Please run the 64 bit server if you are running into errors
 
[14:25:06.459] [1] [Error] [Eco] Error while loading Applied Ecogistics (ItemSystem): System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoad(ReadOnlySpan`1 arrAssembly, ReadOnlySpan`1 arrSymbols)
   at System.Reflection.Assembly.Load(Byte[] rawAssembly, Byte[] rawSymbolStore)
   at ModUtils.assemblyResolve.RegisterEmbeddedAssembly(Assembly assembly, String path)
   at ItemSystem.ItemSystemCore.setupModUtils()
   at ItemSystem.ItemSystemCore..cctor()
 
[14:25:06.459] [5] [ Info] [Eco] Loading mods... Finished in 8 700,6ms
 
[14:25:06.459] [5] [ Info] [Eco] [Server Initialization]... Finished in 9 456,0ms
 
[14:25:06.476] [1] [Error] [Eco] Failed to start the server. Exception was Exception: BadImageFormatException
Message:An attempt was made to load a program with an incorrect format. (0x8007000B)
Source:System.Private.CoreLib

System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoad(ReadOnlySpan`1 arrAssembly, ReadOnlySpan`1 arrSymbols)
   at System.Reflection.Assembly.Load(Byte[] rawAssembly, Byte[] rawSymbolStore)
   at ModUtils.assemblyResolve.RegisterEmbeddedAssembly(Assembly assembly, String path)
   at ItemSystem.ItemSystemCore.setupModUtils()
   at ItemSystem.ItemSystemCore..cctor()
Outer Exceptions:
Exception has been thrown by the target of an invocation.
The type initializer for 'ItemSystem.ItemSystemCore' threw an exception.
 
[14:25:06.476] [1] [ Info] [Eco] Shutdown finished

**Comment by Oddj0bs** [comment]
This si starting Singelplayer world. Works when starting Server then joining

**Comment by cem3cem3** [comment]
I dont support 32 bit mode, however for anyone coming to issue with the same problem, fill out this survey so I can see if I should: https://forms.gle/un9CKVSJbiS4y4fh6

**Comment by Oddj0bs** [comment]
The thing is that i have 64 bit on my computer, so don´t know why game running 32 bit in solo. But it is 64 bit when i host server. So actually it´s only Solo that starts 32 bit some how

**Comment by cem3cem3** [comment]
Single player always launches the 32-bit server. However, the mod should now run in 32 bit mode along with other platforms.
